services:
  jenkins:
    image: jenkinsci/blueocean
    ports:
      - "8010:8080"
    environment:
      DOCKER_HOST: tcp://docker:2376
    volumes:
      - jenkins-data:/var/jenkins_home
    depends_on:
      - docker

  docker:
    image: docker:dind
    privileged: true

volumes:
  jenkins-data: