---
-   name: Create agent user
    user:
      name: jenkins
      password: '!'
      groups:
        - docker
      state: present

-   name: Install software
    apt:
      name:
        - git
        - make
        - gettext-base
      state: present
      update_cache: yes

-   name: Set periodic Docker prune
    cron:
      name: docker-prune
      job: 'docker system prune -af --filter "until=$((7*24))h"'
      minute: '0'
      hour: '1'